willianjusten/awesome-svg

topics/Videos.md
Update with *The SVG Reality* by Sebastiaan Deckers in *Videos* section.
=> update video section

.gitignore, gulpfile.js, package.json, site/page.html
=> init site generator

topics/Fragments.md
=> add article "Caching SVG Sprite in localStorage"

topics/Basics.md
Just found those cool people created a place dedicated for SVG.  
Perhaps it can be integrated with this awesome repo in some way?
=> add a new link

topics/Slides.md
add slideshow "Building Better Interfaces with SVG by Sara Soueidan" - fix #97
=> add slideshow "Building Better Interfaces with SVG by Sara Soueidan"

topics/Videos.md
The Wonderful World of SVG by Mr. Chris Coyier at CSSConf :)
=> add video "The Wonderful World of SVG"

topics/Downloads.md
Dando uma garimpada é possível achar coisas boas nesse site.
=> Adicionando link para o site openclipart.org

topics/Animation.md
=> Animate SVG with CSS

topics/Tutorials.md
=> Caching SVG Sprite in localStorage

topics/Slides.md
Presentation about The Wonderful World of SVG by Chris Coyier
=> Added new slide on the list

topics/Icons.md
JavaScript library for synergistic SVG icons. It works with HTML5 data attributes. There is a primary and a secondary icon and they can be animated with hover and click.
=> Update Icons.md with hybicon.js

topics/Filters.md
Here is a [source code] (https://github.com/AlexanderKozhevin/svg-convolution-matrix).
=> FeConvolveMatrix filter live demo.

topics/Downloads.md, topics/Icons.md
Two links added: 
`topics/Icons.md`
* [svg-icon](https://github.com/leungwensen/svg-icon) - An ultimate svg icons collection DONE RIGHT
`topics/Downloads.md`
* [svg-icon](http://leungwensen.github.io/svg-icon/) - Select and download SVG icons as SVG symbol sprite file from over 4,000 SVG icons transformed from icon fonts collections.
=> add svg-icon project to the list.

topics/Libraries.md
Hey man, I am adding a new library I wrote. I would be glad if you have a look at it and merge the pull request.
Thanks
=> Added libraries -> SVGMaster

topics/Patterns.md
[svg-patterns](https://github.com/derhuerst/svg-patterns) lets you create SVG patterns programmatically to visualize data.
=> add svg-patterns library

topics/Libraries.md
=> Add GraphicsJS

topics/Icons.md
Feather is a collection of **simply beautiful open source icons**. Each icon is designed on a 24x24 grid with an emphasis on simplicity, consistency and legibility.
[feathericons.com](https://feathericons.com)
=> Add Feather to Icons section

Readme.md
Small fix at License title in readme
=> Fix markdown

topics/Softwares.md
Added another one online SVG editor.
=> Added CleverBrush

topics/Downloads.md, topics/Icons.md
disclosure: note that, I maintain the websites I added.
I hope they add a good value to this list, feel free to not include if not, cheers!
=> 1 broken link removed, 2 links added

topics/Videos.md
add a playlist from Kevin Powell
=> add A beginners guide to SVG

topics/Patterns.md
This website does not exists anymore.
=> Remove svggeneration.com
